// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: proto/vm.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MinecraftServiceClient is the client API for MinecraftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinecraftServiceClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
}

type minecraftServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMinecraftServiceClient(cc grpc.ClientConnInterface) MinecraftServiceClient {
	return &minecraftServiceClient{cc}
}

func (c *minecraftServiceClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, "/vm.MinecraftService/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinecraftServiceServer is the server API for MinecraftService service.
// All implementations must embed UnimplementedMinecraftServiceServer
// for forward compatibility
type MinecraftServiceServer interface {
	Start(context.Context, *StartRequest) (*StartResponse, error)
	mustEmbedUnimplementedMinecraftServiceServer()
}

// UnimplementedMinecraftServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMinecraftServiceServer struct {
}

func (UnimplementedMinecraftServiceServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedMinecraftServiceServer) mustEmbedUnimplementedMinecraftServiceServer() {}

// UnsafeMinecraftServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinecraftServiceServer will
// result in compilation errors.
type UnsafeMinecraftServiceServer interface {
	mustEmbedUnimplementedMinecraftServiceServer()
}

func RegisterMinecraftServiceServer(s grpc.ServiceRegistrar, srv MinecraftServiceServer) {
	s.RegisterService(&MinecraftService_ServiceDesc, srv)
}

func _MinecraftService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinecraftServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vm.MinecraftService/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinecraftServiceServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MinecraftService_ServiceDesc is the grpc.ServiceDesc for MinecraftService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinecraftService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vm.MinecraftService",
	HandlerType: (*MinecraftServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _MinecraftService_Start_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/vm.proto",
}
